name: 'Check SSM Command Status'
description: 'A reusable action to check the status of an AWS SSM command'
inputs:
  aws-region:
    description: 'AWS region'
    required: true
  command-id:
    description: 'The ID of the AWS SSM command'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check command status
      shell: bash
      run: |
        COMMAND_ID="${{ inputs.command-id }}"
        AWS_REGION="${{ inputs.aws-region }}"

        sleep 10 # Initial wait for command execution start

        while true; do
            INVOCATIONS_JSON=$(aws ssm list-command-invocations --command-id "$COMMAND_ID" --details --region "$AWS_REGION" --query "CommandInvocations[*].{InstanceId:InstanceId,Status:Status}" --output json)
            STATUS=$(echo $INVOCATIONS_JSON | jq -r '.[].Status')
            echo "Current status: $STATUS"

            if [[ "$STATUS" == "Success" || "$STATUS" == "Failed" || "$STATUS" == "Cancelled" || "$STATUS" == "TimedOut" ]]; then
                INSTANCE_IDS=$(echo $INVOCATIONS_JSON | jq -r '.[].InstanceId')
                for INSTANCE_ID in $INSTANCE_IDS; do
                    echo "Fetching details for instance: $INSTANCE_ID"
                    aws ssm get-command-invocation --command-id "$COMMAND_ID" --instance-id "$INSTANCE_ID" --region "$AWS_REGION" --query "{Status:Status,StandardOutputContent:StandardOutputContent,StandardErrorContent:StandardErrorContent}" --output text
                done
                if [[ "$STATUS" == "Success" ]]; then
                    echo "Command executed successfully."
                    break
                else
                    echo "Command failed with status: $STATUS"
                    exit 1
                fi
            fi

            sleep 10 # Check every 10 seconds
        done