export const QUERY_KEYS = {
  TABLE: "table",
  TABLES: "tables",
  ORDERED: "ordered",
  ORDER: "order",
  ORDERS: "orders",
  CATEGORY: "category",
  CATEGORIES: "categories",
  SUBCATEGORY: "sub-category",
  SUBCATEGORIES: "sub-categories",
  PRODUCT: "product",
  PRODUCTS: "products",
  SALES: "sales",
  USER: "user",
  USERS: "users",
  LOGIN: "login",
  LOGOUT: "logout",
  TODAYORDER: "today-order",
  OCCUPIEDTABLE: "occupied-table",
  SETTINGS: "settings",
  SPECIAL: "special",
  SPECIALS: "specials",
  EXPENSE: "expense",
  EXPENSES: "expenses",
  RESERVATION: "reservation",
  RESERVATIONS: "reservations",
  RESERVATIONTABLES: "reservationTables",
};

export const companyInfo = {
  number: "+977 9761426264",
  address: "Babarmal, Kathmandu",
  whatsAppLink: "https://wa.me/9761426264",
  whatsAppNumber: "+977 9761426264",
};
